services:
  dpostgres:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bibliotheque
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer-db
    restart: always
    ports:
      - "8081:8080"

  api:
    build: .
    container_name: gestion-bibliotheque
    ports:
      - "8082:8080"


  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '8085:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '9025:25'

volumes:
  pgdata:


